# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "529f335a66e6b1b2924ba30c1b8630b4"
name = "cart-transform-poc"
application_url = "http://localhost:3000"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_cart_transforms,read_cart_transforms"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[auth]
redirect_urls = [ "http://localhost:3000/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
